# -*- coding: utf-8 -*-
# batch-23 part3: TraitsPedia (9 essays), Unit Naming Options, Unit Naming, UnitHelp, Units.xml
T = {}

T["TXT_KEY_TRAIT_AGGRESSIVE_PEDIA"]="[TAB]这是一项好战者的特性。你的大多数单位（其实是游戏中最出色的单位——近战与火药单位）都能获得一项免费晋升，还有廉价的兵营与干船坞来提供额外晋升。你若身为侵略型却不去开战，那就是在浪费这项特性。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_BRONZE_WORKING]青铜术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_IRON_WORKING]炼铁术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CIVIL_SERVICE]文官制度[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MACHINERY]机械[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_GUNPOWDER]火药[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CHEMISTRY]化学[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_RIFLING]来复枪[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_STEEL]钢铁[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_ASSEMBLY_LINE]流水线[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_HEROIC_EPIC]英雄史诗[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_WEST_POINT]西点军校[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_RED_CROSS]红十字会[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_PENTAGON]五角大楼[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_STATUE_OF_ZEUS]宙斯神像[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_BARRACKS]兵营[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_DRYDOCK]干船坞[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_STABLE]马厩[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_VASSALAGE]封臣制[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_THEOCRACY]神权政治[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_NATIONHOOD]民族国家[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_POLICE_STATE]警察国家[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_STATE_PROPERTY]国有制[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]怎么运用这项特性？战争。废话。我说得还不够明白吗？赶紧拼凑一支大军去干掉谁吧。[NEWLINE]你会希望你的部队主要由能从这项特性获益的单位组成：近战单位（战士、斧兵、剑士、矛兵、锤兵、长枪兵）、火药单位（火枪兵、来复枪兵、掷弹兵、步兵、防空步兵、陆战队、机械化步兵）及其特色单位变体。[NEWLINE]干船坞让钢铁成为优先科技；同理，能解锁上述某个单位的科技也是如此。要注意，有些侵略型领袖拥有能从这项特性获益的特色单位（蒙特祖玛、亚历山大、德川、拉格纳、夏卡），有些则没有（成吉思、忽必烈、斯大林）。不过后者仍能受惠于廉价的兵营。另外记住，你需要的不只是近战与火药单位——攻城武器与骑乘单位或许得不到侵略特性的免费“战斗I”，但它们仍不可或缺。[NEWLINE]宙斯神像这项世界奇迹很值得拥有——主要是为了不让你要攻打的对象拥有它。战争厌倦本就够糟了；让它翻倍，必定会给你征服世界的计划添堵。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]侵略特性本身没有经济上的优势，事实上还可能过分怂恿你背上过多的经济负担。记住，每个单位都有维护成本，而单位离开本土后成本还会上升。此外，每座被征服的城市都有维护成本。过度征服，尤其是在游戏早期，可能与过度扩张一样糟糕。[NEWLINE]好的一面是，既然侵略特性应当意味着你拥有更出色的单位，但愿你需要的单位数量会更少。"

T["TXT_KEY_TRAIT_CHARISMATIC_PEDIA"]="[TAB]魅力特性随《军阀》资料片一同引入（连同帝国与保护），无疑是这三项新特性中最出色的一项。它显然是一项好战者的特性，主要因为它降低了每次晋升所需的经验值。通过早期开战，你能积攒起一支高度晋升的老兵部队，并随着游戏推进不断升级他们。[PARAGRAPH:1]该特性与两座建筑带来的额外幸福度也有助于好战，因为它减轻了战争厌倦。它还应当在财政上助你一臂之力；无论你走商业经济、专家经济还是混合经济，因幸福上限提高而增加的人口，总意味着更强的经济。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MYSTICISM]神秘主义[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_AGRICULTURE]农业[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_ANIMAL_HUSBANDRY]畜牧业[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_RADIO]无线电[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MASS_MEDIA]大众传媒[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_STONEHENGE]巨石阵[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_HEROIC_EPIC]英雄史诗[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_WEST_POINT]西点军校[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_EIFFEL_TOWER]埃菲尔铁塔[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_PENTAGON]五角大楼[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_MONUMENT]纪念碑[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_BARRACKS]兵营[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_STABLE]马厩[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_DRYDOCK]干船坞[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_BROADCAST_TOWER]广播塔[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_VASSALAGE]封臣制[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_THEOCRACY]神权政治[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]身为魅力型领袖时，趁早开战去收集那些晋升、组建你的老兵之师。开启蛮族、乃至狂暴蛮族，能让你更快积攒更多晋升，因此等你处理完蛮族、准备转身对付邻居时，很可能已拥有一支强大的军队。[PARAGRAPH:1]另外务必善用那提高了的幸福上限。早期以增长为先：确保每座城市都有优质食物资源，直奔陶艺以便建造粮仓，还要建造工人，好让你多出来的市民都有改良过的地块可供工作。尽可能地砍林抢建工人和移民，以催快建造、让城市尽快恢复人口增长。[PARAGRAPH:1]神秘主义与大众传媒是显而易见的科技目标，用以解锁提升幸福的建筑（可惜这些建筑并不因该特性而变廉价；魅力是少数没有廉价建筑的特性之一）。或者，你也可以直奔无线电、建造埃菲尔铁塔，它会在你每一座城市里赠送一座免费的广播塔。[PARAGRAPH:1]巨石阵也是一座颇具吸引力的奇迹，因为它在每座城市里赠送一座免费的纪念碑。不过要记住，一旦你研发出历法（BtS 中是天文学），那些纪念碑便会魔法般地消失。相比之下，广播塔和埃菲尔铁塔永不过时。此外，你直接建造的任何纪念碑都会留存下来产出文化，且文化在一千年后翻倍。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]如上所述，魅力虽增强了两座建筑的效果，却没有廉价建筑，这一局限只有财政和帝国两项特性与之相同。[PARAGRAPH:1]要在早期增长与需要大量工人（以确保那些额外市民有改良地块可供工作）之间取得平衡，可能颇为棘手。除了确保每座城市至少有一处食物资源，还要设法确保它有森林可供砍林抢建工人。"

T["TXT_KEY_TRAIT_CREATIVE_PEDIA"]="[TAB]创意在游戏早期威力强大，让你得以迅速扩张边界，从而占据领土与资源。《军阀》2.08 补丁加入了廉价的图书馆——游戏中最出色的建筑之一——使这项特性更上一层楼。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_WRITING]文字[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_DRAMA]戏剧[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CONSTRUCTION]建筑学[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET]无[PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_LIBRARY]图书馆[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_THEATRE]剧院[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_COLOSSEUM]斗兽场[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_FREE_SPEECH]言论自由[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]创意带来的最大好处，是让你在城市选址与早期城市建造上有更大的自由。你无需操心为了能即刻取用某项关键资源而把城市恰好建在其第一环可工作地块内；建城之后短短几回合，那资源便可供工作了。你也可以省去纪念碑、巨石阵，以及传播某种宗教（好吧，至少后者可以稍微放松些）。[PARAGRAPH:1]此外，创意或许能让你在游戏早期与邻近文明就某处关键资源地块的争夺中占得先机。同理，若地图条件合适，你可以借这项特性在咽喉要地封锁领土。创意也算是一项防御性特性，是保护的表亲。通过更早扩张边界、用你的文化浸润那些地块，敌人要攻打你就得跋涉更多领土。其他文明也更难通过城市选址或征服城市从你手中夺走地块。创意还能更快提升城市的文化防御，使其更难被征服。[PARAGRAPH:1]文字解锁该特性的廉价图书馆，因此它显然比以往更为重要。廉价的剧院与斗兽场是否有用，取决于你的策略与游戏中的处境。你或许想在游戏中期或后期开战，以便物尽其用，用它们减轻战争厌倦。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]创意是一项在游戏早期极为有用、却随游戏推进而日渐式微的特性。随着游戏进程推移、每座城市积累起更多产出文化的方式，+2[ICON_CULTURE] 的作用会越来越小。而且那些廉价建筑都是早期建筑，且本就相对廉价，因此其更快的建造速度到后期会愈发不明显。在多数游戏进行到中盘时，创意特性基本上已无足轻重。"

T["TXT_KEY_TRAIT_EXPANSIVE_PEDIA"]="[TAB]扩张乍看之下并不怎么起眼。事实上，它起初看似属于“弱势”特性一类，就像保护。毕竟，健康并非大问题；在游戏早期束缚你增长的是幸福。而一旦你习惯了那些在城市周围飘荡的病恹恹的绿藤，你就会意识到它的效果通常没那么糟。健康问题不过是稍稍拖慢增长罢了。[PARAGRAPH:1]可且慢。粮仓——对扩张型领袖而言很廉价——是游戏中最有用的建筑之一。有谷物时，它们提供额外的健康。但更重要的是，它们让你能够善用奴隶制，更快地把被牺牲掉的人口重新养回来。[PARAGRAPH:1]而随着《军阀》2.08 补丁，扩张凭借略微廉价的工人得到了一次亟需的增强。你总能用得上更多工人，尤其是在游戏早期。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_POTTERY]陶艺[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_COMPASS]指南针[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_BRONZE_WORKING]青铜术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MATHEMATICS]数学[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_HANGING_GARDEN]空中花园[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_NOTRE_DAME]巴黎圣母院[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_GRANARY]粮仓[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_HARBOR]港口[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_SLAVERY]奴隶制[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]直奔陶艺。建造（或鞭挞抢建）你的廉价粮仓。再多鞭挞几座，然后不停地鞭挞。[PARAGRAPH:1]研读一下如何最好地善用奴隶制政策，以最大化鞭挞带来的锤子溢出，让你鞭挞的那次建造与随后一次建造都变得更廉价。多亏了粮仓，人口会更快养回来，让你得以再度鞭挞他们。[PARAGRAPH:1]显然，多造些工人，因为它们对你而言更廉价，并让它们干活。更快地改良你的地块、连通你的资源。只需记住，工人建造 +25% 的加速靠的是锤子而非食物，因此你需要在建造工人期间改良一些高产地块并工作它们，才能享受到这一好处。既然港口廉价，就设法占据几座沿海城市，好善用这一廉价建筑的优势。[PARAGRAPH:1]另外留心机会去善用那 +2 健康。早期你可以把城市直接建在丛林正中，例如，或建在被泛滥平原环绕之处。此外，你可以建造熔炉、工厂这类减健康的建筑，而无需太过顾虑它们对健康的冲击。你可以多砍些森林，因为你不需要它们的健康好处（因此青铜术与数学科技才有吸引力）。只需记住，这项特性并不能让你的城市无懈可击，你终究得操心它们的健康——只是来得晚些罢了。[PARAGRAPH:1]空中花园对扩张型是一座颇具吸引力的奇迹。它起初或许看似不然——我都已经有健康加成了，为何还要更多？正因为你在推行一种把城市健康推向极限的策略，所以才需要。我偏爱那些能进一步增强某项特性好处的奇迹与建筑（这也是我扮演哲学型领袖时喜欢尝试建造帕特农神庙的原因）。空中花园还提供更多可供鞭挞的市民。而且——还有通往大工程师的伟人点数！你不会不喜欢这个吧。[PARAGRAPH:1]巴黎圣母院也可能派上用场。你若鞭挞到双手流血，那座大教堂的幸福加成或许会大受欢迎。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]与创意等许多其他特性一样，扩张的效果随游戏推进而递减。会出现其他提升健康的手段，那些廉价建筑都是早期建筑，而到了游戏末尾，一旦你的铁路网建成，你那大量廉价的工人便开始闲置。你也可能弃用奴隶制政策，从而失去廉价粮仓的一大好处。[PARAGRAPH:1]而且与多数其他特性一样，扩张不提供任何直接的经济好处。"

T["TXT_KEY_TRAIT_FINANCIAL_PEDIA"]="[TAB]这很可能是最强的特性，至少在皇帝难度以下如此，强到许多玩家都视财政为一根“拐杖”，因觉得它带来了不公平的优势而避开拥有此特性的领袖。游戏开发者显然也有同感，故而在早期一个补丁里，他们移除了银行的双倍生产速度以削弱其威力。即便如此，财政仍是一项真正令人惊叹的特性。[PARAGRAPH:1]起初，它显得如此微妙：某些地块上 +1[ICON_COMMERCE]？那又如何？[PARAGRAPH:1]答案当然是这样：笨蛋，问题在经济。军事、研究、宗教等游戏要素你爱怎么说都行；归根结底，你的文明需要一个稳健的经济来支撑你所做的其余一切。军事单位会产生维护成本，出了本土更甚。城市同样有维护成本，掣肘你的扩张速度，还要求你确保每座城市都能以某种方式自给。而要在科技上跟上，你必须能拨出资金来支持研究。财政特性让所有这些任务都稍微轻松一些——若运用得当，则轻松得多。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_POTTERY]陶艺[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CURRENCY]货币[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_GUILDS]行会[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_BANKING]银行业[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_LIBERALISM]自由主义[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_PRINTING_PRESS]印刷术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_DEMOCRACY]民主[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CORPORATION]公司[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_COLOSSUS]太阳神巨像[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_WALL_STREET]华尔街[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_MARKET]市场[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_GROCER]杂货店[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_BANK]银行[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_LIBRARY]图书馆[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_UNIVERSITY]大学[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_OBSERVATORY]天文台[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_LABORATORY]实验室[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_FREE_SPEECH]言论自由[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_EMANCIPATION]废奴解放[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]善用财政特性的主要方式非常直白：狂铺村庄。没错，就是那久经检验的商业经济，即 CE。让你的 [LINK=UNIT_WORKER]工人[\\\\LINK]在人口能工作的范围内尽可能多地铺设 [LINK=IMPROVEMENT_COTTAGE]村庄[\\\\LINK]，同时也兼顾其他值得工作的地块。我尤其偏爱把村庄铺在临河的草原地块上，因为村庄一建成，财政好处便立刻生效，而那 2 点食物又养活了工作该地块的市民（3 点食物的泛滥平原用来铺村庄更佳，可同时支撑城市增长与经济）。只需记住，你或许得改用农场灌溉其中一些地块，以养活并增长你的人口，和/或串联灌溉另一地块。不过务必让市民稳定地工作那些村庄，因为这是让它们成长、增加收益的唯一途径。[PARAGRAPH:1]此外，留心那些提供额外商业的资源。宝石、黄金和白银是显而易见的目标，香料、丝绸和葡萄酒也不错；它们除了资源本身的额外商业外，都会为你带来 +1[ICON_COMMERCE] 的好处。你要占据这些资源，确保它们在某座城市的工作范围内、经过改良、并有市民工作。多数商业丰厚的资源还提升幸福，这意味着你能把其他城市养得更大，进而工作更多村庄与其他商业丰厚的地块。[PARAGRAPH:1]既然你会有那么多额外商业滚滚而来，就优先建造那些能利用它的建筑，以及解锁它们的科技。图书馆、修道院、大学、天文台和实验室都能倍增你通过科研滑块从商业转化的研究量，而市场、杂货店和银行则倍增剩下的金币。此外，印刷术会提升你村庄投资的产出，言论自由政策亦然。废奴解放会让任何尚未成熟的村庄更快成长。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]首先，财政对任何不提供至少 2 点商业的地块都不给予直接好处。这可能让你不愿工作没有好处的地块，即便你需要工作它们。这意味着一座主要工作锤子丰厚而非商业丰厚地块的生产型城市，从这项特性中得不到直接好处。然而你需要至少一座、最好更多的生产型城市，因此别为了商业城市而忽视它们。地块改良也是同理。没错，你可以在草原丘陵上铺村庄。可你应该这么做吗？矿场能提供亟需的锤子，而这正是商业城市常年长期缺乏的东西。[PARAGRAPH:1]然而，财政最大的问题在于你经济的脆弱，尤其是随着时间推移。村庄要长成城镇需要很多回合，可这份投资却能被几个劫掠的敌方单位迅速毁掉。而劫掠村庄所能获取的那笔不可小觑的金币，对 AI 极具诱惑。你若开战，就得用防劫掠单位驻守你最好、最悠久的商业城市。也要设法让你最好的商业城市位于内陆、深处帝国腹地，而非更易受攻的边境或海岸线上。"

T["TXT_KEY_TRAIT_IMPERIALIST_PEDIA"]="[TAB]在以尤利乌斯·凯撒身份打了几局单机之后，我对这项特性的评价有所改观。我原本把它归入“弱势”一类，如今却觉得它属于“中等”——只要运用得当。[PARAGRAPH:1]帝国以两种方式支持侵略性扩张。首先，移民建造更廉价，让你在游戏早期得以更快地圈地。其次，为了善用那提高的大军事家诞生率，你被鼓励通过侵略去扩张。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_BRONZE_WORKING]青铜术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MASONRY]砌石术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MATHEMATICS]数学[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CODE_OF_LAWS]法典[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_FASCISM]法西斯主义[\\\\LINK][PARAGRAPH:1][ICON_BULLET]所有军事科技[PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_GREAT_WALL]长城[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_MT_RUSHMORE]拉什莫尔山[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_BARRACKS]兵营[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_VASSALAGE]封臣制[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_THEOCRACY]神权政治[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_POLICE_STATE]警察国家[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]显然，在游戏早期推行 REX（快速扩张）策略，并在你的核心城市站稳后，继之以侵略型、好战者的扩张政策。这尤其适合俄罗斯的叶卡捷琳娜大帝，因为她的创意特性与早期圈地策略有明确的协同。[PARAGRAPH:1]要记住，移民产量的提高来自锤子而非食物。这意味着在游戏早期改良地块时，你会想像农场和牧场一样多地关注矿场。砍林与鞭挞贡献锤子，因此那些也被该特性倍增——青铜术与数学的吸引力正源于此。[PARAGRAPH:1]你可以通过建造长城进一步增强那提高的大军事家诞生率。除了把蛮族挡在外面，那座奇迹还为发生在你文化边界内的战斗提供 +100% 的大军事家诞生率，结果是在你自己领土内防御时，配合该特性可获得 +200% 的大军事家加成。因此，扮演拥有此特性的领袖时，砌石术与一处石料来源很可能是优先项。[PARAGRAPH:1]在最初的 REX 阶段结束后，善用帝国特性的主要途径很简单：战争。趁早开战，频频开战。这是产生大军事家的唯一途径（并记住，与蛮族作战能挣经验，却挣不到通往大军事家的点数）。大军事家其实是游戏中最有用的伟人之一，即便它缺少其他伟人的某些用途（比如点亮科技或开启黄金时代）。你可以把他们附到单位上以超级晋升，或安置在城中提供额外经验、或用军事学院提升单位产量。只需记住优先研发法典与法院，好让你不断扩张的帝国在经济上维持可行。[PARAGRAPH:1]许多玩家偏爱把第一位大军事家与一个单位结合，赋予它军医I、II、III 晋升。这个军医单位会更快治愈你的部队群，让它们更早重返战场。你也可以用一位大军事家赋予某单位领导力晋升，这与帝国特性形成协同，因为该晋升使那单位在其幸存的每场战斗中获得双倍经验，而那双倍经验在计入你下一位大军事家时又被再翻一番。你还可以把大军事家与一艘卡拉维尔帆船结合，赋予它侧翼I、航海I 和航海II，以近乎必然地赢得环航加成。[PARAGRAPH:1]既然你在追求好几位大军事家（且很可能把大部分策略都建立在其好处之上），你会想先抢下研发法西斯主义所赠的那位免费大军事家。以你将要进行的种种好战之举，你横竖都会想建造拉什莫尔山、施行警察国家来缓解一部分战争厌倦。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]嗯，首先，它没有廉价建筑，也没有经济优势。帝国按理说应当有廉价的法院，可组织已经拥有那些了，把它们挪走会严重削弱那项特性。或许监狱本会是帝国的一个不错的廉价建筑。倘若《文明IV》有实用的堡垒，那么这些堡垒更快的建造速度对该特性也会合乎逻辑。[PARAGRAPH:1]然而，取代廉价建筑的是一个廉价单位。可帝国对移民建造的加成来自锤子而非食物。这意味着你在游戏早期得背道而驰，建造矿场以确保你的移民建造能享受到这项特性。倘若食物也能加速移民的建造，这会是一项强得多的特性。[PARAGRAPH:1]然而，该特性最大的弱点，在于它把你锁进了一种特定策略。拥有侵略特性时你不必扮演好战者；你可以善用它去建立一支强大的军队与军事基础设施（毕竟廉价的兵营与干船坞计入你的军力评级），从而让人不敢来犯、任你埋头发展。可有了帝国，你就非好战不可。除了与其他文明作战，别无途径去挣得那些大军事家。除非你正有心大打出手，否则别选这项特性，不然就是在浪费它。"

T["TXT_KEY_TRAIT_INDUSTRIOUS_PEDIA"]="[TAB]如果说侵略是好战者的特性，那么勤劳便是建造者的特性。奇迹更廉价，增强了它们“哦——闪闪发光”的吸引力，并在争建它们的竞赛中让你抢占先机。此外，熔炉——一种让其他建筑造得更快的建筑——嗯，本身也造得更快。[PARAGRAPH:1]自《超越刀锋》资料片以来，这如今是《文明IV》最专属的俱乐部，尽管优势不大。所有其他特性都有 9 到 10 位领袖拥有，而勤劳仅由 8 位领袖共享。而且不，仍然没有勤劳/哲学的特性组合；这显然被游戏设计者视为过于强大。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MASONRY]砌石术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MONOTHEISM]一神论[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_METAL_CASTING]金属铸造[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_ASSEMBLY_LINE]流水线[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET]呃……几乎所有奇迹。好吧，也许除了奇琴伊察。[PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_FORGE]熔炉[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_FACTORY]工厂[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_ORGANIZED_RELIGION]规范宗教[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_STATE_PROPERTY]国有制[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_CASTE_SYSTEM]种姓制度[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_ENVIRONMENTALISM]环境保护[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]当然是建造奇迹。建造它们、善用它们，并把它们挡在 AI 那双肮脏的小手之外。也要留心并占据那些加速奇迹的资源，如铜、铁、大理石和石料。记住，加速的奇迹产量同样适用于国家奇迹。[PARAGRAPH:1]另外，优先研发金属铸造以取用你的廉价建筑。对勤劳型领袖极具协同效应的一个战术是：建造神谕（一座奇迹，因此更廉价）并选金属铸造作为免费科技。然后去建造熔炉。记住熔炉也是铁厂、太阳神巨像、埃菲尔铁塔和自由女神像等更多奇迹的必需品。既然金属铸造能解锁它，太阳神巨像通常在其未来所在城市的熔炉建成后紧接着建造。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]扮演勤劳型领袖时，做一个“建筑狂”那海妖歌般的诱惑更加强烈。奇迹虽更廉价，却仍非便宜到尘埃里。它们需要投入可观的锤子，而这些锤子本可派上更好的用场。一如既往，务必确保你选择建造的奇迹契合你的策略与游戏中的处境。"

T["TXT_KEY_TRAIT_ORGANIZED_PEDIA"]="[TAB]尽管组织有一项直接的经济好处——降低政策的开销——但在这方面它远不及财政那般给力。尽管如此，省下的每回合金币终究是省下了，不容小觑。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MONOTHEISM]一神论[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CODE_OF_LAWS]法典[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_SAILING]航海术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_ASSEMBLY_LINE]流水线[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_GREAT_LIGHTHOUSE]亚历山大灯塔[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_FORBIDDEN_PALACE]紫禁城[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_CRISTO_REDENTOR]救世基督像[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_COURTHOUSE]法院[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_LIGHTHOUSE]灯塔[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_FACTORY]工厂[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_SLAVERY]奴隶制[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_ORGANIZED_RELIGION]规范宗教[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_BUREAUCRACY]官僚政治[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_POLICE_STATE]警察国家[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_STATE_PROPERTY]国有制[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]与虔诚相似，能解锁政策的科技——尤其是高开销政策——是优先项。不过与虔诚不同，切换政策并非要频频去做的事（除非你是阿育王，他在这方面兼得二者之长）。也记得选择某项政策是因为你能从中获益，而不仅仅因为它可用，或因为组织会让它变廉价。[PARAGRAPH:1]然而，组织带来的最大好处，是那些廉价建筑——游戏中最出色的三座之一。要善用灯塔，就设法建造几座沿海城市。廉价的法院让新城更廉价，因此你可以把它用于 REX 策略、好战、或两者兼施。[PARAGRAPH:1]事实上，我倾向于把组织视作一项好战者的特性（尤其对汉谟拉比、尤利乌斯·凯撒和拿破仑而言，他们的搭档特性同样对好战友好）。这是因为我在被征服城市里的第一个建造项便是法院，以降低其维护成本，而组织让那些法院造起来——或鞭挞起来——更廉价。[PARAGRAPH:1]最后，工厂是游戏后期最出色的建筑之一，而 2.08 补丁已让它们对组织变廉价。[PARAGRAPH:1]科技优先项显然是航海术、法典和流水线以取用那些廉价建筑。其他科技目标是那些能解锁某些更有用但昂贵政策的科技，尤其是通向强大官僚政治政策的文官制度。它高昂的维护成本对组织型领袖将减半，从而提升其效用。规范宗教（由一神论解锁）与警察国家（由法西斯主义解锁）亦然。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]与许多特性一样，随着游戏推进，组织日渐式微。你的经济壮大，高开销政策渐渐变得负担得起。因此，2.08 补丁加入一座后期廉价建筑（工厂），是对组织在游戏后期一次受欢迎的增强。尽管如此，组织最好的时期无疑是中盘，那时你多半正施行官僚政治与规范宗教，并仍在建设你的经济。"

T["TXT_KEY_TRAIT_PHILOSOPHICAL_PEDIA"]="[TAB]正如财政特性适合商业经济，哲学特性适合专家经济（SE）。SE 自然拥趸众多，而关于哪种经济最优的争论仍在激烈进行。[PARAGRAPH:1]只需这么说就够了：SE 在哲学型领袖手中最为强大，因为运营那么多专家会带来多得多的伟人。你不必用哲学型领袖跑 SE，正如你可以不带财政特性跑 CE，但 SE 与哲学特性二者结合时都最为强大。[PARAGRAPH:1]伟人当然有许多用途。在专家经济中，他们主要用于“点灯”，即用伟人去研发出一项科技，通常免研究点数。你随后可以拿这项“免费科技”去换取你从其他文明那里需要的科技。这让你在大半局游戏中都能把研究滑块开到 0%，而依靠科学家与科技交易的组合来跟上研究。（一言以蔽之，这就是我版本的 SE。）[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_WRITING]文字[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_POLYTHEISM]多神论[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CODE_OF_LAWS]法典[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_PHILOSOPHY]哲学[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_EDUCATION]教育[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_BIOLOGY]生物学[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_PYRAMID]金字塔[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_PARTHENON]帕特农神庙[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_GREAT_LIBRARY]大图书馆[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_STATUE_OF_LIBERTY]自由女神像[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_NATIONAL_PARK]国家公园[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_LIBRARY]图书馆[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_UNIVERSITY]大学[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_PACIFISM]和平主义[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_REPRESENTATION]代议制[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_CASTE_SYSTEM]种姓制度[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_MERCANTILISM]重商主义[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]我不会详述如何跑 SE，因为那超出了本文的范围。姑且这么说：我对哲学特性的建议是跑 SE，或至少跑一种“混合经济”，其中一些城市专注食物与专家，另一些专注村庄与商业。（混合经济尤其适合英格兰的伊丽莎白，她拥有财政特性——如上所述，这需要一定量的狂铺村庄才能充分善用。）[PARAGRAPH:1]在 SE 社群内部，关于建造金字塔的重要性众说纷纭。金字塔对 SE 的吸引力在于能极早地在游戏中施行代议制政策。在标准尺寸地图上，这项政策提升你五座最大城市（早期很可能是你仅有的城市）的幸福上限。这让你能把那些城市养得更大，从而工作更多农场、运营更多专家。此外，在代议制下，每位专家除了通常贡献的研究点外，还额外贡献三点研究——连通常毫不贡献研究的专家也算，如工程师、祭司、商人和普通市民专家。在代议制下，艺术家和间谍的科研贡献从 1 升至 4，而科学家的贡献从 3 翻倍至 6。显然，金字塔与早期代议制会为 SE 注入超强动力，但许多人坚称 SE 没有那座奇迹或那项政策也能过得去。[PARAGRAPH:1]帕特农神庙对哲学型领袖也可能是一座有用的奇迹。你既已依赖伟人换取科技，何不建一座能增加你所获伟人数量的奇迹呢？[PARAGRAPH:1]文字会是一项早期优先科技，好让你建造图书馆、运营你的第一批科学家。奇迹会非常有用，因为它们全都贡献伟人点数；去追求那些贡献你最想要、最需要之伟人类型点数的奇迹。既然大科学家通常是最有用的伟人，那就使大图书馆对拥有哲学特性的领袖成为一座极具吸引力的奇迹。重商主义为每座城市贡献一名免费专家，自由女神像亦然（且没有重商主义“不得建立对外贸易路线”的代价）。种姓制度政策对 SE 与哲学特性是一大福音，让你能运营一座城市所能支撑的尽可能多的商人、科学家和/或艺术家。因此法典是一项优先科技。教育解锁哲学特性的廉价建筑——大学，因此它也是优先项。哲学使和平主义政策可用，它为拥有你国教的城市再提供 +100% 的伟人产量加成。生物学能让你把城市养得更大、支撑更多专家，因此在游戏后期优先研发它。[PARAGRAPH:1]国家公园国家奇迹有利于 SE，因为它让每一片森林保护区多出 1 名免费专家。不过这意味着你得当心在你建造它的那座城市的工作范围内保留一些森林，乃至丛林。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]运营专家经济所需的微操，远比运营更直白的村庄经济多得多。游戏会玩得更久，你需要把一切都管得紧密得多。那种玩法并非人人适合。[PARAGRAPH:1]哲学特性与 SE 的好处在游戏后期开始消退。伟人的产出愈发昂贵、出现得愈发稀疏，而科技对你的专家与更少的伟人来说，也变得太贵而无法高效研究。到这时你最好已处在能取胜的位置，否则你可能很快发现自己落后了。要么如此，要么你就得转型为村庄经济；切换到废奴解放政策将是达成这一转型的关键。[PARAGRAPH:1]与财政特性不同，哲学特性不提供任何直接的经济好处。你得另寻他法来维持你的经济不倒。"

T["TXT_KEY_TRAIT_PROTECTIVE_PEDIA"]="[TAB]这是《军阀》资料片引入的又一项新特性，看来并未经过深思熟虑。我把它视作最弱特性之一，这不该令人意外，因为这一看法为多数玩家所共有——尽管我承认保护确有它的拥趸。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=TECH_ARCHERY]箭术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MASONRY]砌石术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_POLYTHEISM]多神论[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_SAILING]航海术[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_FEUDALISM]封建制度[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_MACHINERY]机械[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_ENGINEERING]工程学[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_GUNPOWDER]火药[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_CHEMISTRY]化学[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_RIFLING]来复枪[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_ASSEMBLY_LINE]流水线[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_TEMPLE_OF_ARTEMIS]阿尔忒弥斯神庙[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_GREAT_LIGHTHOUSE]亚历山大灯塔[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_CHICHEN_ITZA]奇琴伊察[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_BARRACKS]兵营[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_WALLS]城墙[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_CASTLE]城堡[\\\\LINK][PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_VASSALAGE]封臣制[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=CIVIC_THEOCRACY]神权政治[\\\\LINK][PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]保护虽弱，却并非毫无用处。当你占领一座城市时，你那些获免费晋升的单位更有本钱守卫你的新领地，而它极有可能招来反攻。事实上，你的火药单位有可能身兼攻守二职。（不过多数箭术单位是孱弱的进攻者，最好只用于防御。）[PARAGRAPH:1]你若有一处石料来源，城墙与城堡便更加廉价，让它们造起来不那么费劲。配合阿尔忒弥斯神庙与亚历山大灯塔这类奇迹，你可以把保护的廉价城堡纳入一种贸易路线经济，这在中盘时期可能大有裨益。在 BtS 中，你也可以用廉价城堡来辅助谍报。事实上，一些玩家已开始玩一种 EP，即“谍报经济”，在字母表之后把科研滑块调至 0%，其余大部分科技通过窃取科技获得。[PARAGRAPH:1]大概最受惠于这项特性的文明是中国，因为其特色单位是游戏中最出色的箭术单位之一——诸葛弩，它能够、也应当被用作进攻单位。操演I 只会增强它的威力，在它 2 次免费先制之外再赋予一次额外的先制机会。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]保护特性的问题在于它本质上主要是防御性的。免费的城市驻防晋升，只在单位于城中遭受攻击时才有用。城墙与城堡——本就相当廉价，令其双倍生产速度不那么诱人——同样只在你遭受攻击时才有用。唯有免费的操演I 是一项进攻晋升，可你多久用箭术单位进攻一次呢？当然，除非它们是诸葛弩。（尽管它对你更具侵略性的火药单位可能有益。）[PARAGRAPH:1]在《文明IV》里打防御战的问题在于，AI 太喜欢劫掠了。你的单位若龟缩在城墙之后，AI 便会兴高采烈地把你视线内每一处地块改良劫掠殆尽，让你的经济一路螺旋崩溃。你的单位必须走出城市去守卫你的领土，这就让城墙与城堡近乎无用——城市驻防晋升同理。[PARAGRAPH:1]从许多方面看，保护特性的加入似乎更多是为了造福 AI 而非人类玩家。AI 大体上偏爱打防御，因此保护契合它的程序设定。任何人类玩家都会告诉你，去硬撼据守于丘陵城市、有城堡城墙掩护的保护型长弓兵，可能相当唬人——尽管当然并非不可逾越。多带几门投石车赴会便是。"

T["TXT_KEY_TRAIT_SPIRITUAL_PEDIA"]="[TAB]与财政一样，虔诚的巨大力量来自它对你经济的正面影响。无政府状态意味着有一个或更多回合，你的城市不增长、不建造任何东西，你的文化不增加，伟人点数不积累，村庄不成长，如此种种。虔诚意味着你避开那些经济停滞的时期；相较于一个非虔诚文明，这应当会让你能够多研究至少一两项科技、多建造若干单位与建筑、多产出伟人，如此种种。[PARAGRAPH:1]与其他几项特性不同，虔诚的效果不会在游戏后期减弱。恰恰相反，随着更多政策与宗教变得可用，你或许想要、也需要更频繁地切换政策，而虔诚让你得以如此。[PARAGRAPH:1]然而在我看来，这项特性已从最强特性之一滑落为一项中等强度的特性。这主要归因于《超越刀锋》资料片。坦白说，许多人一开始就对我把它归入“强势”一类有异议。可《超越刀锋》通过让其效果更易获得，削弱了它的强度。你现在只需动用一位伟人、而非两位，便能开启你的第一个黄金时代；而且你现在能在黄金时代期间无政府状态地切换政策。这只是《超越刀锋》中黄金时代被改进、变得更有吸引力的众多方式之一。[PARAGRAPH:1]此外，在游戏后期，当你能取用所有政策、虔诚通常最为强大之时，你现在可以通过建造新的救世基督像奇迹达成同样的效果——它不仅赋予你虔诚那种无政府状态切换政策的能力；你甚至可以切换政策而无需等待一次回合切换，更别说通常的五回合了！（注意：在 BtS 3.13 补丁中，这已改为政策切换之间等待 1 回合。）[PARAGRAPH:1]所以在我看来，虔诚从强势跌为中等，并非因其自身有何过错，而是因非虔诚型领袖也能更易获得它的好处。[PARAGRAPH:1][H1]高优先级科技[\\\\H1][PARAGRAPH:1][ICON_BULLET]那些能解锁政策的（如 [LINK=TECH_CODE_OF_LAWS]法典[\\\\LINK]）[PARAGRAPH:1][ICON_BULLET]那些能创立宗教的（如 [LINK=TECH_MEDITATION]冥想[\\\\LINK]）[PARAGRAPH:1][ICON_BULLET][LINK=TECH_DIVINE_RIGHT]君权神授[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=TECH_PAPER]造纸术[\\\\LINK][PARAGRAPH:1][H1]有用的奇迹[\\\\H1][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_PYRAMID]金字塔[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_SANKORE]桑科尔大学[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_SPIRAL_MINARET]螺旋尖塔[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_APOSTOLIC_PALACE]使徒宫[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_SHWEDAGON_PAYA]仰光大金塔[\\\\LINK][PARAGRAPH:1][ICON_BULLET][LINK=BUILDING_SISTINE_CHAPEL]西斯廷礼拜堂[\\\\LINK][PARAGRAPH:1][H1]最佳建筑[\\\\H1][PARAGRAPH:1][ICON_BULLET]神庙[PARAGRAPH:1][ICON_BULLET]修道院[PARAGRAPH:1][H1]有用的政策[\\\\H1][PARAGRAPH:1][ICON_BULLET]几乎所有政策——只要它提供值得的好处、契合你的策略，就切换过去。[PARAGRAPH:1][H1]如何运用[\\\\H1][PARAGRAPH:1]没有无政府状态意味着你可以当下就采用一项政策，一旦它可用便立即获得其优势，而不必像一位审慎的非虔诚型领袖那样等着一次性切换好几项政策。因此，倘若某项政策对你有益，就别犹豫，切换过去。你唯一的约束，是要等五个回合才能再度切换政策。[PARAGRAPH:1]还有外交上的好处。你可以轻易改宗某种宗教，或切换到某项偏好政策去讨好另一个文明。一旦你从他们那里得到所需——比如一次科技交易——你就能同样轻易地把宗教或政策切回来。不过要记住，共享宗教或偏好政策带来的外交加成，可能需要好几回合才能积累到显著的程度。[PARAGRAPH:1]金字塔对虔诚型领袖是一座颇具吸引力的奇迹，因为它能在早期解锁所有政府政策，让你在游戏早期便善用这项特性。显然，任何能解锁政策的科技都很宝贵，都应优先——只要那政策值得。在《超越刀锋》中，仰光大金塔也很有吸引力，因为它是金字塔的宗教对应物，能解锁所有宗教政策。[PARAGRAPH:1]神庙是不起眼的建筑，产出 +1 文化并让一名市民保持幸福。然而，你若建造螺旋尖塔（由君权神授解锁）、桑科尔大学（造纸术）和使徒宫（神学），虔诚的廉价神庙便能真正大放异彩。这些奇迹分别让你国教的神庙产出 +1 金币、+2 研究和 +2 锤子。（请注意，你即便不建使徒宫，只要把使徒宫的宗教定为国教，仍能让所有宗教建筑获得其 +2 锤子加成。）只需知道，建造这些奇迹中的一座或多座，会让自由宗教政策变得不吸引人，并降低那些会令这些奇迹过时的计算机与大众传媒的优先级。[PARAGRAPH:1][H1]不利之处[\\\\H1][PARAGRAPH:1]虔诚与创意这类特性正好相反：它在游戏早期政策寥寥无几时极为孱弱。它的好处要到后来、随着更多政策上线才显现。现实地说，你的政策切换大多会发生在中盘，尽管这显然会因情况而异，但在多数游戏里，我发现自己在后期对虔诚特性的利用要少一些。[PARAGRAPH:1]此外，虔诚虽能让你“省钱”，却不像财政那样，这项特性并不直接产出金钱。你一如既往地需要一个稳健的经济。[PARAGRAPH:1]扮演虔诚型领袖时，你可能受诱惑，一旦某项政策可用便立即切换过去。记住，某些政策的维护成本相比其他政策要高；切换之前，先确保该政策在某方面确实值得。也记住，仅仅因为某项政策变得可用，并不意味着它在游戏那个阶段对你必然最优。审慎权衡你的选择，务必让你的政策契合你的整体策略与游戏中的处境。[PARAGRAPH:1]要获得廉价神庙的好处，你需要一个国教。因此你要么得创立一种宗教，要么得有一种宗教传播到你这里。此外，你或许需要、或想要极早地采用一个国教，而那可能给你带来外交上的连锁反应。"

# --- Unit Naming Options.xml ---
T["TXT_KEY_BUG_OPT_UNITNAMING__ENABLED_TEXT"]="启用"
T["TXT_KEY_BUG_OPT_UNITNAMING__ENABLED_HOVER"]="勾选后，使用本标签页及 INI 文件中的格式来为玩家的单位命名。"
T["TXT_KEY_BUG_OPT_UNITNAMING__USEADVANCED_TEXT"]="使用高级方法"
T["TXT_KEY_BUG_OPT_UNITNAMING__USEADVANCED_HOVER"]="勾选后，将使用 'Adv Unit Naming.ini' 文件中的高级命名规范（Era_UnitClass 选项参见该 ini 文件）。"
T["TXT_KEY_BUG_OPT_UNITNAMING__DEFAULT_TEXT"]="命名规范：默认"
T["TXT_KEY_BUG_OPT_UNITNAMING__DEFAULT_HOVER"]="输入用户自定义的命名规范（详见帮助文件）。名称可由纯文本与出现在成对脱字符（^）之间的格式代码组合而成。[NEWLINE][ICON_BULLET]例如 \"^cv^ ^ut^ from ^ct^\" --> \"波士顿的美利坚弓手\"[NEWLINE][BOLD]通用代码[\\\\BOLD][NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]civ4[COLOR_REVERT] - 使用内置的 Civ4 名称[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]rd[COLOR_REVERT] - 随机名称[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]rc[COLOR_REVERT] - 随机的文明相关名称[NEWLINE][BOLD]单位信息代码[\\\\BOLD][NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]ct[COLOR_REVERT] - 建造该单位的城市（例如波士顿）[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]cv[COLOR_REVERT] - 建造该单位的文明的形容词形式（例如美利坚）[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]ut[COLOR_REVERT] - 单位类型（例如弓手）[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]cb[COLOR_REVERT] - 战斗类型（例如近战）[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]dm[COLOR_REVERT] - 领域类型（例如水域）[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]ld[COLOR_REVERT] - 建造该单位的领袖（例如罗斯福）[NEWLINE][BOLD]计数代码[\\\\BOLD][NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]cnt[f][COLOR_REVERT] - 跨所有单位计数[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]cntu[f][COLOR_REVERT] - 按单位类型计数[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]cntct[f][COLOR_REVERT] - 按城市计数[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]cntuct[f][COLOR_REVERT] - 按单位/城市组合计数[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]cntc[f][COLOR_REVERT] - 按战斗类型计数[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]cntd[f][COLOR_REVERT] - 按领域计数[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]tt1[f][x:y][COLOR_REVERT] - 计数至一个在 x 与 y 之间选取的数字[NEWLINE][ICON_BULLET][COLOR_HIGHLIGHT_TEXT]tt1[f][x][COLOR_REVERT] - 从 x 开始计数，每次 tt1 代码被重置时递增[NEWLINE][NEWLINE]* [f] 中的 f 为 s, A, a, p, g, n, o, r 之一（详见帮助文件）"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_AIR_TEXT"]="命名规范：战斗[AIR]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_AIR_HOVER"]="为 'AIR' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_ARCHER_TEXT"]="命名规范：战斗[ARCHER]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_ARCHER_HOVER"]="为 'ARCHER' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_ARMOR_TEXT"]="命名规范：战斗[ARMOR]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_ARMOR_HOVER"]="为 'ARMOR' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_GUN_TEXT"]="命名规范：战斗[GUN]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_GUN_HOVER"]="为 'GUN' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_HELICOPTER_TEXT"]="命名规范：战斗[HELICOPTER]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_HELICOPTER_HOVER"]="为 'HELICOPTER' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_MELEE_TEXT"]="命名规范：战斗[MELEE]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_MELEE_HOVER"]="为 'MELEE' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_MOUNTED_TEXT"]="命名规范：战斗[MOUNTED]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_MOUNTED_HOVER"]="为 'MOUNTED' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_NAVAL_TEXT"]="命名规范：战斗[NAVAL]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_NAVAL_HOVER"]="为 'NAVAL' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_NONE_TEXT"]="命名规范：战斗[None]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_NONE_HOVER"]="为 'None' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_RECON_TEXT"]="命名规范：战斗[RECON]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_RECON_HOVER"]="为 'RECON' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_SIEGE_TEXT"]="命名规范：战斗[SIEGE]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_SIEGE_HOVER"]="为 'SIEGE' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_DISCIPLE_TEXT"]="命名规范：战斗[DISCIPLE]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_DISCIPLE_HOVER"]="为 'DISCIPLE' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_ADEPT_TEXT"]="命名规范：战斗[ADEPT]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_ADEPT_HOVER"]="为 'ADEPT' 战斗单位输入用户自定义的命名规范。"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_ANIMAL_TEXT"]="命名规范：战斗[ANIMAL]"
T["TXT_KEY_BUG_OPT_UNITNAMING__COMBAT_ANIMAL_HOVER"]="为 'ANIMAL' 战斗单位输入用户自定义的命名规范。"

# --- Unit Naming.xml ---
T["TXT_KEY_BUG_UNIT_NAMING_DOMAIN_LAND"]="陆地"
T["TXT_KEY_BUG_UNIT_NAMING_DOMAIN_SEA"]="海军"
T["TXT_KEY_BUG_UNIT_NAMING_DOMAIN_AIR"]="空中"
T["TXT_KEY_BUG_UNIT_NAMING_DOMAIN_IMMOBILE"]="固定"

# --- UnitHelp.xml ---
T["TXT_KEY_UNIT_AUTORAZE"]="[ICON_BULLET]进入地块时摧毁改良设施（在敌方领土内）与地形特征"
T["TXT_KEY_MISSION_CREATE_GREAT_WORK_HELP"]="此命令将令该单位创造一件伟大杰作，并平息其当前所在城市的叛乱。它会消耗该单位。"
T["TXT_KEY_UNIT_CANNOT_CAPTURE"]="[ICON_BULLET]单位无法俘获"
T["TXT_KEY_UNIT_CANNOT_PILLAGE"]="[ICON_BULLET]单位无法劫掠"
T["TXT_KEY_UNIT_CANNOT_PROTECT_CITY"]="[ICON_BULLET]单位不提供军事幸福"
T["TXT_KEY_UNIT_DURATION"]="持续时间：将在 %d1 [NUM1:回合:回合]后死亡。"
T["TXT_KEY_UNIT_FREE_PROMOTION_PICK"]="[ICON_BULLET]单位起始时拥有 %D1 次免费[NUM1:晋升:晋升]"
T["TXT_KEY_UNIT_HAS_CASTED"]="本回合已经施法"
T["TXT_KEY_UNIT_HELP_DELAYED_CASTING"]="正在施放 %s1_Spell（剩余 %d2_TurnsRemaining [NUM2:回合:回合]）"
T["TXT_KEY_UNIT_HELP_NO_UPKEEP"]="[ICON_BULLET]无需维护费"
T["TXT_KEY_UNIT_INVESTIGATE_CITY"]="[ICON_BULLET]可调查对手城市"
T["TXT_KEY_UNIT_MIN_LEVEL"]="[ICON_BULLET]必须由 %d1 级或更高级的单位升级而来"

# --- Units.xml ---
T["TXT_KEY_UNIT_ABASHI_STRATEGY"]="这位塞安英雄能够喷吐烈焰，她的咆哮会令周遭的敌方单位陷入恐惧。她还免疫魔法，较弱的单位往往会因过于畏惧而不敢攻击她。"
T["TXT_KEY_UNIT_AIR_ELEMENTAL_STRATEGY"]="风元素作为三阶召唤物虽然孱弱，却能越过任何地形，包括水域地块，且视野比其他单位远 2 格。赢得战斗后，风元素会召唤出 [LINK=UNIT_LIGHTNING_ELEMENTAL]光元素[\\\\LINK]。"
T["TXT_KEY_UNIT_ARTHENDAIN_PEDIA"]="整整一个连队都被她屠戮殆尽。她身着一袭褴褛的白裙，一头纠结的红发，二者都像煎锅上的油脂般黏附在她身上。她不带任何武器，她也不需要。她的利爪如铁一般，比任何女孩都强壮。可她不过是个女孩，或至少曾经是。她又抓又咬，咳嗽着、喘息着，逃走了。他们中有一人死了，另有几人受了伤。[PARAGRAPH:1]阿森丹开始为伤口敷上治疗的药膏，可它们已因感染泛起绿色。手指粗的道道裂口迸开，皮肤与肌肉向后翻卷，仿佛想要逃离骨头。他们在剧痛中扭动，不出几分钟便如同遭了鞭笞；再过几分钟，他们看上去就像刚变的丧尸，仍在尖叫，躯体死去而心智尚存。而后终于，仁慈地，他们死了。[PARAGRAPH:1]阿森丹在那场厮杀中毫发无伤，可那疫病仍在蔓延。他抄起弩，一心要确保那女孩不再把她的疫病散播开去。当他握住弩那打磨光亮的握柄时，他注意到自己的双手也开始泛红肿胀。他急忙奔向水边；他们身处普雷斯普尔城下的下水道，平时他绝不会碰这里的水，可它总该好过沾在他身上的东西。他擦洗双手，情形却只是愈发糟糕，随后咳嗽开始了。[PARAGRAPH:1]他听见自己在尖叫，与其他人一模一样。他栽进水里，死了。[PARAGRAPH:1]疫病在水中蔓延；次日清晨，全城本会在一场瘟疫中醒来。到日暮时分，若非苏塞鲁斯出手干预，几乎就无人幸存了。他的影子穿过下水道，把疫病收进一只陶瓶。他向水说话，水便将阿森丹从深处托起，安放在这位神祇脚边。苏塞鲁斯请求得到这矮人的魂灵，阿拉温应允了。[PARAGRAPH:1]阿森丹记不清太多，从擦洗双手到次日清晨在一家本地酒馆醒来，一切都不过是一片模糊。他记得一个治好了他的人。他记得被交予那只瓶子，被叮嘱要妥善保管、永不开启。他记得被告知，他必须找到那个女孩。而直到今日，他仍在朝着那个目标努力。"
T["TXT_KEY_UNIT_BOAR_RIDER_STRATEGY"]="山猪骑兵是游戏中最差的骑手。可这不过是个骑猪的矮人，你还指望什么呢？"
T["TXT_KEY_UNIT_DONAL_PEDIA"]="卢乌是班诺尔的英雄，一位传奇的恶魔与不死者屠戮者。他能在城市中招募单位，且与大指挥官不同，招募并不会牺牲他自身。倘若卢乌证实传说不虚，斩杀恶魔与不死者，他便会重获招募之能，若能在自己的一场场战斗中幸存下来，还可组建起一支庞大的军队。[PARAGRAPH:2]那头追踪他的猎犬起初几乎看似正常，直到它转过身、发出低吼。半张脸已然腐烂，底下的头骨伤痕累累、缺了几块，一个眼窝是黑黢黢的一洞。可它看猎物却毫无障碍。它朝卢乌的喉咙扑去。[PARAGRAPH:1]这远非卢乌见过的第一头地狱犬。反射本能接管了一切，他俯身翻滚，避开了獠牙。他那简陋的武器飞入手中。卢乌与那猎犬相互绕行，佯攻又退回，直到电光石火间一切告终。卢乌闪过那一扑，把刀刃没入这恶魔的脖颈，将它钉在地上。它低吼着，近乎滑稽地翻腾挣扎，想要脱身、继续攻击。[PARAGRAPH:1]“来吧，乖仔，装死，”卢乌说着，把盾牌狠狠砸在那猎犬的头骨上。二者一齐碎裂，翻腾也停了。“真是条好狗。”[PARAGRAPH:1]他不再为自己的俏皮话发笑了。他早在许久之前就不再自寻乐子。十年还是一千年，他毫无概念，也早已不再在意。自他的族人离开地狱，便再没有别人可以发笑了，可他仍在冷峻地与这一界的居民搏杀时插科打诨。在绝望之王的居所里，他最大的战斗，是维系那唯一支撑着他的东西——希望。[PARAGRAPH:2]“我们没有希望了，凯布瑞尔。我们必须放弃围城。”[PARAGRAPH:1]凯布瑞尔转身面向她的外甥。“我们不能，马提乌斯！你听见我从法纳里尔口中听到的话了。‘塞安人取得了突破。有阿加雷斯的指引。’我们必须挺进！”凯布瑞尔说话时颤抖着，她那衰老的身躯近来愈发不听使唤了。倘若她召见麾下议事时不披全副战甲，或许会稳当些，可身为班诺尔的战争领袖，却不时刻备战？[PARAGRAPH:1]“我们的确必须。”大祭司附和道。他很年轻，比他所奏对的这位摄政年轻得多，说起话来却带着无上的自信。“源自加尔维霍姆的种种异端，已足以构成动员的挑衅。因此萨巴曦尔认为我们连与法纳里尔这样的精灵匪徒结交都毫无理由。”[PARAGRAPH:1]马提乌斯嗤之以鼻。“我敢说萨巴曦尔知道把一名探子送入塞安领地的更好办法，可他近来一直不怎么肯明说。”[PARAGRAPH:1]“维内拉特家的家主莫非在质疑祭司团代言的权威……”[PARAGRAPH:1]“艾敏，马提乌斯要指出的是，”凯布瑞尔插话道，“我们需要为我们的任务排定轻重。余灰部落一直在积蓄力量，我们的使节被逐出了拉努恩首都，还有——”[PARAGRAPH:1]战争议事会被一阵剧烈的地震打断，把众人尽数掀翻在地。凯布瑞尔的反射本能战胜了年迈的局限；她一跃而起，冲出帐篷。营地展现出班诺尔纪律的成效，已在指挥官帐篷四周列好阵形，随时准备击退来袭。[PARAGRAPH:1]可这并非一场攻击开场的魔法齐射。全军眼睁睁看着他们下方山坡上的树木与灌丛枯萎死去，太阳被一层阴沉的霾遮蔽，地平线上火焰迸发。这是凯布瑞尔从孩提时代、并在此后无数噩梦中都记忆犹新的一幕。七十年前他们逃离了地狱，如今地狱却找上门来了。[PARAGRAPH:2]他曾走遍这座地狱，寻找一处出口。且不论它是一片无限的界域，他敢发誓自己每一寸都看过两遍了。他一路上被阿加雷斯与巴尔的爪牙追杀，好歹或是甩脱、或是击退了它们。只为得见今日。[PARAGRAPH:1]卢乌看见下方山谷里延展开一道通往凡间的传送门。一道维度的裂隙，剧烈地波动着。而它周围列布着一支恶魔大军。上蹿下跳的小恶魔、一队鲁宾、一整座恶灵之城……还有卢乌所见过最庞大的巨角炎魔。而它们正在离去。“哦，休想撇下我，你们别想，”他喃喃道，动身下了山坡。“我不知道你们要去哪儿，可那总该好过这里。”[PARAGRAPH:1]恶魔们列队穿过，那裂隙则缓缓开始闭合。[PARAGRAPH:2]恶魔们踏上了征途。与它们的第一战令班诺尔大军溃散，自那以后他们被逼退到了托尔莱汉，那是离受污之地最近的定居点。从它的城垛上，凯布瑞尔整夜都能看见与地狱军团接壤处的火焰。至此，祭司们的祝福挡住了污秽，却挡不住那些受污者。它们围住了定居点，那些曾在她年少时缠扰她的恶魔。唯有最勇敢的士兵留下来与它们对峙。[PARAGRAPH:1]战斗在破晓时打响。它很快便对他们不利起来。[PARAGRAPH:1]马提乌斯与他的姨母并肩立于战线上。“我若注定要死，能死在传说中的英雄之一身旁，我倍感荣幸。”[PARAGRAPH:1]凯布瑞尔点点头，挥舞着她的双手巨剑。“我倒宁愿活着。可倘若班诺尔人不挺身面对这可怖的威胁，还有谁会呢？”视野边缘的一个身影令她转过身，与一头狰狞的嗜血兽撞了个正着。[PARAGRAPH:1]“对付这些畜生的诀窍是从背后下手，”一位老友高喊着，那嗜血兽应声倒地。“翅膀限制了它们的余光视野。”[PARAGRAPH:1]“是谁……我的天，是你吗？神子卢乌？”[PARAGRAPH:1]“如假包换，难得地以血肉之躯现身。”[PARAGRAPH:1]马提乌斯倒抽一口气。“那么那些传说……全是真的？我们是萨巴曦尔的班诺尔人！”[PARAGRAPH:1]战局逆转了。班诺尔人阵亡的与幸存的一样多，可城镇得救了，地狱的军队今日被击退了。捷报传开，令那些逃走的人蒙羞，也激励了新的一代。这正是萨巴曦尔一直保全他们以待的那场战争，而它才刚刚开始。可第一场胜利，属于他们。"
T["TXT_KEY_UNIT_EIDOLON_PEDIA"]="因这里，孤然独处，居着一位——其手曾造出[NEWLINE]令世间因惧而战栗的怪异幻影；[NEWLINE]其镌于恐怖典籍中的符文曾昭示[NEWLINE]星渊之外潜伏窥伺的种种存在。[NEWLINE]阿维洛涅的暗黑之主——其窗棂凝望着[NEWLINE]无人目光所能承受的梦之深坑！[NEWLINE][NEWLINE]幻影死灵不侍奉任何主人，却甘愿投身任何殊死的争斗。良善的宗教避这些恶魔造物唯恐不及，或索性搜寻并将其铲除，可那些容忍其邪恶存在的人，会发觉它们是无所畏惧、致命的战士，在任何战场上都几乎无可匹敌。[NEWLINE][NEWLINE]唯有邪恶阵营的玩家才能建造幻影死灵。"
T["TXT_KEY_UNIT_ENGINEER_21"]="机械法师艾罗德"
T["TXT_KEY_UNIT_GILDEN_STRATEGY"]="这位勒约沙尔法英雄是最早期的英雄之一，让精灵得以在对手的城防迫使他们不得不带上魔法单位之前便发动攻势。若在勒约沙尔法的箭术训练场之后建造，他应能受惠于该训练场为弓手提供的 +1 额外攻击强度加成。"
T["TXT_KEY_UNIT_HIGH_PRIEST_OF_LEAVES_STRATEGY"]="森林主教拥有绿树祭司的全部能力，此外，当他们身处森林或远古森林地块时，还能召唤 [LINK=literal]树人[\\\\LINK]。"
T["TXT_KEY_UNIT_HIGH_PRIEST_OF_THE_EMPYREAN_STRATEGY"]="天穹主教，即卢里杜斯，拥有喻所祭司的全部能力，此外还能使用 [LINK=literal]荣耀王冠[\\\\LINK] 法术。该王冠对周遭所有敌人造成伤害，并让施法者能看见隐形单位。"
T["TXT_KEY_UNIT_LIZARDMAN_STRATEGY"]="蜥蜴人与猎人完全相同，唯有种族之别。"
